using System.Collections.Generic;
using System.Linq;

using Psythyst.Data.Entitas;

namespace Psythyst.Plugin.PostProcessor.Entitas
{
    /// <summary>
    /// EntitasFileHeaderPostProcessor Class.
    /// </summary>
    public class EntitasFileHeaderPostProcessor : IPostProcessor<OutputModel>
    {
        public const string AUTO_GENERATED_HEADER_FORMAT =
@"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Psythyst ~ Psythyst.Plugin.PostProcessor.Entitas.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
";

        public int Priority { get { return 100; } }

        public IEnumerable<OutputModel> Process(IEnumerable<OutputModel> Collection)
        {
            return Collection.Select(File => {
                   File.FileContent = $"{AUTO_GENERATED_HEADER_FORMAT}\n{File.FileContent}"; return File;
            });     
        }
    }
}